### ISSUE TITLE
Mem leaks on terminate

### ISSUE THREAD

**Issue by tauraamui** [beholdenspore28/lite-engine#4]
![Screenshot 2024-12-01 01 08 02](https://github.com/user-attachments/assets/7eafaec9-e1c6-49ea-a1c1-ea9e4ee1a306)

So I'm seeing these memory leak errors when I terminate the engine, I think its because you're not deallocing the ECS data?

```c
	ECS_alloc(); 

	// create rocks
	for (int i = 1; i <= 200; i++) {
		int rock = entity_create();

		component_add(rock, COMPONENT_KINEMATIC_BODY);
		component_add(rock, COMPONENT_TRANSFORM);
		component_add(rock, COMPONENT_MESH);
		component_add(rock, COMPONENT_MATERIAL);
		component_add(rock, COMPONENT_SHADER);

		mesh[rock] = mesh_alloc_rock(5, 1);

```

There's no explicit dealloc'ing of the entities or their associated data.

**Comment by beholdenspore28** [comment]
Is this still happening? I've updated the project quite a bit since this was opened.

**Comment by tauraamui** [comment]
Yes, it is.
```
❯ make
mkdir -p build/bin
mkdir -p build/obj
clang -c dep/glad.c -g3 -fsanitize=address  -Wall -Wextra -Wpedantic -std=c99 -ferror-limit=15 -Idep -o build/obj/glad.o
clang build/obj/*.o src/*.c  -Isrc -Idep -lglfw -lGL -lm -g3 -fsanitize=address  -Wall -Wextra -Wpedantic -std=c99 -ferror-limit=15 -o build/bin/lite-engine
time ./build/bin/lite-engine
Rev up those fryers!
Attempting to load shaders 'res/shaders/primitive.vs.glsl' and 'res/shaders/primitive.fs.glsl'
Attempting to load shaders 'res/shaders/unlit.vs.glsl' and 'res/shaders/unlit.fs.glsl'
LLVMSymbolizer: error reading file: No such file or directory

=================================================================
==20632==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 537040 byte(s) in 103 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc8e0  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc8e0) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)

Indirect leak of 1232 byte(s) in 7 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc8e0  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc8e0) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)
    #2 0x7ffcba632c6f  ([stack]+0x1ec6f)

Indirect leak of 880 byte(s) in 5 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc8e0  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc8e0) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)
    #2 0x7ffcba632a2f  ([stack]+0x1ea2f)

Indirect leak of 528 byte(s) in 3 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc8e0  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc8e0) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)
    #2 0x7ffcba632c7f  ([stack]+0x1ec7f)

Indirect leak of 352 byte(s) in 2 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc8e0  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc8e0) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)
    #2 0x7ffcba632a3f  ([stack]+0x1ea3f)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x5582f4fe93be in malloc (/home/tauraamui/src/lite-engine/build/bin/lite-engine+0x1813be) (BuildId: b9ea91abfb93364000de338e8203a2e097a0cb84)
    #1 0x7f09368bc9f7  (/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so+0xbc9f7) (BuildId: c0d9016bc0542e3e94f66cc6a322c19657b54611)

SUMMARY: AddressSanitizer: 540224 byte(s) leaked in 124 allocation(s).
Command exited with non-zero status 1
6.89user 0.57system 0:19.16elapsed 38%CPU (0avgtext+0avgdata 286272maxresident)k
0inputs+0outputs (0major+84654minor)pagefaults 0swaps
make: *** [makefile:32: build_lite_engine] Error 1
```

**Comment by beholdenspore28** [comment]
I see. I think this might be specific to your graphics drivers. I'll do my best to help track it down though. I was having a similar issue a while back but then I updated my drivers and I haven't seen it since.

**Comment by beholdenspore28** [comment]
I am closing this issue. There have been many updates to the engine since this was opened. If it's still a problem, please open a new issue.
